# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    allowed_topics: '%env(string:ALLOWED_TOPICS)%'
    forbidden_words: '%env(string:FORBIDDEN_WORDS)%'
    base_url: '%env(string:BASE_URL)%'
    faq_data: '%kernel.project_dir%/config/faq.php'
    history_config: '%kernel.project_dir%/config/history_config.php'
    history_storage: '%kernel.project_dir%/storage/history.json'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Services
    App\Service\TopicService:
        arguments:
            $allowedTopics: '%allowed_topics%'
            $forbiddenWords: '%forbidden_words%'
    App\Service\Product\ProductUrlGenerator:
        arguments:
            $baseUrl: '%base_url%'
    App\Service\Product\ProductImageService:
        arguments:
            $baseUrl: '%base_url%'
    App\Service\FaqService:
        arguments:
            $faq: '%faq_data%'
    App\Service\HistoryService:
        arguments:
            $historyConfig: '%history_config%'
            $historyStorage: '%history_config%'
#    App\Service\SessionService:
##        arguments:
##            $session: '@session.factory'
